version: "3.3"  # optional since v1.27.0
services:
    mongo:
        # pitfall: remember to use a initialization script to initialize your database
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=root
            - MONGO_INITDB_DATABASE=test
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
            ME_CONFIG_MONGODB_SERVER: mongo
    # spider:
    #     build: ./spider
    #     ports:
    #         - "8000:8000"
    #     volumes:
    #         - ./spider:/opt/spider/
    #         - logvolume01:/var/log
volumes:
    logvolume01: {}