version: "3.3"  # optional since v1.27.0
services:
  spider:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/spider/
      - logvolume01:/var/log
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Password_#123
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Password_#123
volumes:
  logvolume01: {}